[package]
name = "paratrooper"
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.26"
egui-macroquad = "0.12.0"
quad-rand = "0.2.1"
